// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package DNZ_app

import (
	"database/sql"
	"time"
)

type Customer struct {
	ID          int64
	Name        string
	Phonenumber sql.NullString
	Role        string
}

type OpenOrder struct {
	ID            int64
	Productmenuid int64
	Customerid    sql.NullInt64
	Date          time.Time
	Summary       int64
	Status        string
	Itemsordered  string
}

type Product struct {
	ID            int64
	Productmenuid int64
	Title         string
	Price         int64
	Served        int64
	Category      string
}

type ProductMenu struct {
	ID            int64
	Date          time.Time
	Startregister int64
	Activity      string
}
